# Setup

In [1]:
# ! pip install datasets
# ! pip install pandas
# ! python.exe -m pip install --upgrade pip
# ! pip install matplotlib

In [2]:
from datasets import load_dataset
import pandas as pd

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
def pd_set_see_full_dataframe():
    # Permanently changes the pandas settings
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)
    # pd.set_option('display.max_colwidth', -1)

def pd_reset_options():
    # Resets the options
    pd.reset_option('all')

def display_whole_df(df):
    pd_set_see_full_dataframe()
    display(df)
    pd_reset_options()

## Imports and Merge

## Fa-kes

In [5]:
df_fa_kes = pd.read_csv('../data/crime/fa-kes/FA-KES-Dataset.csv',encoding='latin-1')
df_fa_kes.head()

,unit_id,article_title,article_content,source,date,location,labels,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1914947530,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,nna,4/5/2017,idlib,0,NaN,NaN,NaN,NaN
1,1914947532,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,nna,4/7/2017,homs,0,NaN,NaN,NaN,NaN
2,1914947533,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,nna,4/16/2017,aleppo,0,NaN,NaN,NaN,NaN
3,1914947534,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,nna,4/19/2017,aleppo,0,NaN,NaN,NaN,NaN
4,1914947535,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,nna,7/10/2016,aleppo,0,NaN,NaN,NaN,NaN

In [6]:
df_fa_kes = df_fa_kes[['article_title','article_content','labels','date','location', 'source']]

In [7]:
df_fa_kes.head()

,article_title,article_content,labels,date,location,source
0,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,0,4/5/2017,idlib,nna
1,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,0,4/7/2017,homs,nna
2,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,0,4/16/2017,aleppo,nna
3,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,0,4/19/2017,aleppo,nna
4,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,0,7/10/2016,aleppo,nna

In [8]:
display(df_fa_kes['labels'].value_counts())
df_fa_kes['labels'].replace({0:False, 1:True}, inplace=True)
df_fa_kes['labels'].replace({False:1, True:0}, inplace=True)
display(df_fa_kes.head())
display(df_fa_kes['labels'].value_counts())

labels
1    426
0    378
Name: count, dtype: int64

,article_title,article_content,labels,date,location,source
0,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,1,4/5/2017,idlib,nna
1,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,1,4/7/2017,homs,nna
2,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,1,4/16/2017,aleppo,nna
3,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,1,4/19/2017,aleppo,nna
4,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,1,7/10/2016,aleppo,nna

labels
0    426
1    378
Name: count, dtype: int64

In [9]:
df_fa_kes.rename(columns={'article_title':'title','article_content':'text', 'labels':'label'}, inplace=True)
display(df_fa_kes.head())

,title,text,label,date,location,source
0,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,1,4/5/2017,idlib,nna
1,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,1,4/7/2017,homs,nna
2,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,1,4/16/2017,aleppo,nna
3,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,1,4/19/2017,aleppo,nna
4,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,1,7/10/2016,aleppo,nna

In [10]:
df_fa_kes = df_fa_kes[['text', 'label']].assign(metadata=df_fa_kes.iloc[:,2:].agg(dict,1))
display(df_fa_kes.head())

,text,label,metadata
0,Wed 05 Apr 2017 Syria attack symptoms consiste...,1,"{'label': 1, 'date': '4/5/2017', 'location': '..."
1,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,1,"{'label': 1, 'date': '4/7/2017', 'location': '..."
2,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,1,"{'label': 1, 'date': '4/16/2017', 'location': ..."
3,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,1,"{'label': 1, 'date': '4/19/2017', 'location': ..."
4,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,1,"{'label': 1, 'date': '7/10/2016', 'location': ..."

In [11]:
df_fa_kes.to_feather('../data/FA-KES-Dataset.feather')

In [12]:
df = pd.read_feather("../data/FA-KES-Dataset.feather")

In [13]:
display(df.head())

,text,label,metadata
0,Wed 05 Apr 2017 Syria attack symptoms consiste...,1,"{'date': '4/5/2017', 'label': 1, 'location': '..."
1,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,1,"{'date': '4/7/2017', 'label': 1, 'location': '..."
2,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,1,"{'date': '4/16/2017', 'label': 1, 'location': ..."
3,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,1,"{'date': '4/19/2017', 'label': 1, 'location': ..."
4,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,1,"{'date': '7/10/2016', 'label': 1, 'location': ..."

## Snopes

In [15]:
df_emergent = pd.read_csv('../data/crime/snopes/snopes_phase2_clean_2018_7_3.csv')
df_emergent.head()

,fact_rating_phase1,snopes_url_phase1,article_title_phase1,article_category_phase1,article_date_phase1,article_claim_phase1,article_origin_url_phase1,index_paragraph_phase1,page_is_first_citation_phase1,error_phase2,original_article_text_phase2,article_title_phase2,publish_date_phase2,author_phase2
0,true,https://www.snopes.com/fact-check/is-trump-adm...,Is the Trump Administration Paying Southwest K...,Politics Politics,22 June 2018,The Trump administration is paying Southwest K...,https://www.dallasnews.com/news/immigration/20...,1,True,No Error,"A Southwest Key spokeswoman, Cindy Casares, ha...",Texas nonprofit has received $1.5 billion in f...,2018-06-19,Jennifer Emily
1,true,https://www.snopes.com/fact-check/is-trump-adm...,Is the Trump Administration Paying Southwest K...,Politics Politics,22 June 2018,The Trump administration is paying Southwest K...,https://www.bloomberg.com/news/articles/2018-0...,1,False,No Error,The Trump administration plans to pay a Texas ...,Trumps Immigrant Child Detentions Mean $458 Mi...,2018-06-19,Alex Wayne
2,true,https://www.snopes.com/fact-check/is-trump-adm...,Is the Trump Administration Paying Southwest K...,Politics Politics,22 June 2018,The Trump administration is paying Southwest K...,https://web.archive.org/web/20180604042055/htt...,10,False,No Error,Who We Are Southwest Key Programs is a private...,Who We Are: Southwest Key Programs,NaN,NaN
3,true,https://www.snopes.com/fact-check/is-trump-adm...,Is the Trump Administration Paying Southwest K...,Politics Politics,22 June 2018,The Trump administration is paying Southwest K...,https://www.hhs.gov/about/budget/fy2018/budget...,10,False,No Error,Administration for Children and Families : Dis...,FY 2018 Budget in Brief - ACF - Discretionary,2017-05-19,NaN
4,true,https://www.snopes.com/fact-check/is-trump-adm...,Is the Trump Administration Paying Southwest K...,Politics Politics,22 June 2018,The Trump administration is paying Southwest K...,https://www.justice.gov/opa/pr/attorney-genera...,11,False,No Error,Attorney General Jeff Sessions today notified ...,Attorney General Announces Zero-Tolerance Poli...,NaN,NaN

In [16]:
pd_set_see_full_dataframe()
display(df_emergent['article_category_phase1'].value_counts())
pd_reset_options()

article_category_phase1
Fake News                                   2264
Fauxtography                                1624
Uncategorized                               1463
Politics                                    1288
Politics  Politics                           808
Medical                                      693
Politicians  Politics                        585
Science                                      432
Crime                                        311
Business                                     263
Entertainment                                253
Critter Country                              252
Viral Phenomena                              248
Conspiracy Theories  Politics                241
History                                      217
Food                                         213
Ballot Box  Politics                         209
Politics  Politicians                        166
Crime  Politics                              157
Medical  Science                             127
Questionable Quotes                          120
Inboxer Rebellion                            119
Science  Medical                             107
Politics  Conspiracy Theories                103
Military                                     103
Technology                                   102
Sports                                       100
Legal  Politics                               97
Politics  Immigration                         92
Religion                                      92
Immigration  Politics                         87
Guns  Politics                                85
Politics  Guns                                79
Politics  Quotes                              78
Media Matters                                 70
Politics  Environment                         69
Legal Affairs                                 68
Politics  Religion                            61
Fake News  Politics                           58
Politics  Fake News                           58
Politics  Science                             57
Fauxtography  Politics                        49
Horrors                                       48
Guns                                          47
Politics  Sexuality                           47
Holidays                                      46
Racial Rumors                                 42
Politics  Business                            41
Viral Phenomena  Superstition                 40
Disney                                        40
Viral Phenomena  Politics                     38
Politics  Fauxtography                        37
Military  Politics                            35
Computers                                     35
Politics  Race                                35
Glurge Gallery                                31
Fraud & Scams                                 31
Politics  Legal                               29
September 11th                                27
Medical  Politics                             27
Sports  Politics                              27
Hurricane Katrina                             26
Politics  Medical                             26
Politics  Military                            23
Politicians                                   23
Superstition                                  22
Language                                      22
Business  Politics                            22
Politics  Ballot Box                          22
Fauxtography  Fauxtography                    21
Humor                                         21
Politics  Entertainment                       20
Fake News  Fake News                          19
Inboxer Rebellion  Viral Phenomena            18
Fauxtography  Medical                         18
Fauxtography  Viral Phenomena                 18
Religion  Religion                            17
Fake News  Crime                              16
Fake News  Religion                           16
Questionable Quotes  Questionable Quotes      15
Sports  Sports                                14
Entertainment  Viral Phenomena                14
History  Politics                             13
Politics  Crime                               13
Business  Food                                13
Racial Rumors  Questionable Quotes            13
Ballot Box                                    13
Racial Rumors  Politics                       13
Immigration                                   13
Viral Phenomena  Conspiracy Theories          13
War/Anti-War                                  13
Technology  Technology                        12
Viral Phenomena  Fauxtography                 12
History  Computers                            12
Viral Phenomena  Fake News                    12
Politics  History                             12
Lost Legends                                  11
Uncategorized  Uncategorized                  11
Fake News  Entertainment                      11
Science  Politics                             11
Viral Phenomena  Entertainment                11
Religion  Politics                            11
Science  Military                             11
Critter Country  Medical                      11
Fauxtography  History                         11
Politics  Viral Phenomena                     11
Business  History                             10
Religion  Science                             10
Critter Country  Fauxtography                 10
Fauxtography  Entertainment                   10
Food  Politics                                10
Politics  Media Matters                        9
Military  September 11th                       9
Food  Food                                     9
Travel                                         9
College                                        9
Technology  Medical                            9
Medical  Medical                               8
Politicians  Religion                          8
Soapbox                                        8
Media Matters  Politics                        8
Politics  War/Anti-War                         8
Viral Phenomena  Medical                       8
History  Religion                              8
Politics  Language                             8
Fauxtography  Technology                       8
Humor  Politics                                8
Quotes                                         8
History  Medical                               7
History  Racial Rumors                         7
Automobiles                                    7
Fake News  Fauxtography                        7
Old Wives' Tales  Medical                      7
Conspiracy Theories                            7
Fauxtography  Science                          7
Viral Phenomena  Food                          7
Politics  Racial Rumors                        7
Science  Fauxtography                          7
Racial Rumors  Horrors                         7
Entertainment  Crime                           7
Religion  Racial Rumors                        7
History  Science                               7
Food  Science                                  7
Risqué Business                                7
Medical  Critter Country                       6
Medical  Business                              6
Business  Risqué Business                      6
Entertainment  Risqué Business                 6
Fauxtography  Legal Affairs                    6
Medical  Fake News                             6
Business  Technology                           6
Fake News  Food                                6
Science  Science                               6
Entertainment  History                         6
Controversy                                    6
Entertainment  Fauxtography                    6
Science  Environment                           6
Religion  Fake News                            6
Legal                                          5
Science  Entertainment                         5
Viral Phenomena  Viral Phenomena               5
Embarrassments                                 5
Sexuality                                      5
Disney  Entertainment                          5
Old Wives' Tales                               5
Food  Medical                                  5
Fake News  History                             5
Medical  Inboxer Rebellion                     5
Crime  Viral Phenomena                         5
Conspiracy Theories  Science                   5
Racial Rumors  College                         5
Science  Critter Country                       4
Legal Affairs  Science                         4
Automobiles  Fauxtography                      4
Fake News  Politicians                         4
Science  Fake News                             4
Politics  Embarrassments                       4
Fake News  Superstition                        4
Language  Viral Phenomena                      4
Technology  Fake News                          4
Politics  Questionable Quotes                  4
Humor  Media Matters                           4
Critter Country  Media Matters                 4
Entertainment  Politics                        4
Quotes  Questionable Quotes                    4
Entertainment  Media Matters                   4
History  Sports                                4
Inboxer Rebellion  Legal Affairs               4
Military  Science                              4
Technology  Crime                              4
Language  Politics                             4
Fake News  Risqué Business                     3
Viral Phenomena  Fraud & Scams                 3
Questionable Quotes  History                   3
Fauxtography  Inboxer Rebellion                3
Business  Critter Country                      3
Crime  Crime                                   3
Politics  Legal Affairs                        3
Crime  Fauxtography                            3
Ballot Box  Questionable Quotes                3
Food  Fauxtography                             3
Ballot Box  Religion                           3
Fake News  Medical                             3
Business  Fake News                            3
Entertainment  Questionable Quotes             3
Medical  Viral Phenomena                       3
Fauxtography  Sports                           3
Automobiles  Racial Rumors                     3
Science  Travel                                3
Race  Politics                                 3
Viral Phenomena  Inboxer Rebellion             3
Entertainment  Fake News                       3
Fake News  Military                            3
Fauxtography  Racial Rumors                    3
Viral Phenomena  Sports                        3
Fake News  Quotes                              3
Fake News  Science                             3
Risqué Business  Politics                      3
Entertainment  Sports                          3
Viral Phenomena  Critter Country               3
Holidays  Religion                             2
Critter Country  Politics                      2
September 11th  September 11th                 2
Fake News  Inboxer Rebellion                   2
Fauxtography  Humor                            2
Conspiracy Theories  Religion                  2
Politics  Risqué Business                      2
Crime  Fraud & Scams                           2
Politics  Controversy                          2
Holidays  Politics                             2
Business  Fauxtography                         2
Politics  Critter Country                      2
Cokelore                                       2
Viral Phenomena  College                       2
Fake News  Viral Phenomena                     2
Questionable Quotes  Politics                  2
Quotes  Medical                                2
History  Viral Phenomena                       2
Sports  Military                               2
Immigration  Religion                          2
Humor  Language                                2
Fauxtography  Hurricane Katrina                2
Viral Phenomena  Travel                        2
Politics  Technology                           2
Automobiles  Viral Phenomena                   2
Fake News  Sports                              2
Fauxtography  Travel                           2
Critter Country  Viral Phenomena               2
Medical  Love                                  2
Viral Phenomena  Crime                         2
Politics  Superstition                         2
Computers  Fake News                           2
Sports  Fake News                              2
Superstition  Entertainment                    2
Technology  Viral Phenomena                    2
Viral Phenomena  Technology                    2
Technology  Politics                           2
Fake News  Critter Country                     2
Fake News  College                             2
Food  Luck                                     1
Racial Rumors  Fake News                       1
Ballot Box  Sports                             1
History  Language                              1
Crime  Fake News                               1
Viral Phenomena  Business                      1
Media Matters  Fake News                       1
Entertainment  Horrors                         1
Food  Horrors                                  1
Holidays  Fauxtography                         1
Quotes  Politics                               1
Critter Country  Travel                        1
Religion  Fauxtography                         1
Politics  Soapbox                              1
Automobiles  Horrors                           1
Inboxer Rebellion  Politics                    1
Language  Medical                              1
Humor  Viral Phenomena                         1
Holidays  Food                                 1
Racial Rumors  Entertainment                   1
Fauxtography  Critter Country                  1
Military  Fake News                            1
Politicians  Racial Rumors                     1
Automobiles  Holidays                          1
Risqué Business  Medical                       1
Conspiracy Theories  Medical                   1
Media Matters  Media Matters                   1
Critter Country  Fake News                     1
Weddings  Weddings                             1
Viral Phenomena  Computers                     1
Business  Entertainment                        1
Name: count, dtype: int64

C:\Users\user\AppData\Local\Temp\ipykernel_161048\1255536759.py:10: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option('all')

In [17]:
df_test = df_emergent[df_emergent['article_category_phase1'].str.contains("Crime")==True]

In [18]:
df_test['article_category_phase1'].value_counts()

article_category_phase1
Crime                     311
Crime  Politics           157
Fake News  Crime           16
Politics  Crime            13
Entertainment  Crime        7
Crime  Viral Phenomena      5
Technology  Crime           4
Crime  Fauxtography         3
Crime  Crime                3
Viral Phenomena  Crime      2
Crime  Fraud & Scams        2
Crime  Fake News            1
Name: count, dtype: int64

In [19]:
df_test.head()

,fact_rating_phase1,snopes_url_phase1,article_title_phase1,article_category_phase1,article_date_phase1,article_claim_phase1,article_origin_url_phase1,index_paragraph_phase1,page_is_first_citation_phase1,error_phase2,original_article_text_phase2,article_title_phase2,publish_date_phase2,author_phase2
174,true,https://www.snopes.com/fact-check/italian-econ...,Was an Italian Economist Removed from a Plane ...,Crime,18 April 2018,"Guido Menzio, an Italian economist, was remove...",https://www.washingtonpost.com/news/rampage/wp...,2,False,No Error,11:20 a.m.: This post has been updated to incl...,"Ivy League economist ethnically profiled, inte...",2016-05-07,Catherine Rampell
175,true,https://www.snopes.com/fact-check/italian-econ...,Was an Italian Economist Removed from a Plane ...,Crime,18 April 2018,"Guido Menzio, an Italian economist, was remove...",http://nymag.com/daily/intelligencer/2016/05/e...,9,False,No Error,"On Thursday, an American Airlines flight from ...","Flight Delayed, Economist Questioned After Doi...",2016-05-07,NaN
176,true,https://www.snopes.com/fact-check/italian-econ...,Was an Italian Economist Removed from a Plane ...,Crime,18 April 2018,"Guido Menzio, an Italian economist, was remove...",http://archive.is/LITGj,10,False,No Error,It was true. It's the state of the world (and ...,Snopes,2018-04-18,NaN
186,true,https://www.snopes.com/fact-check/jamie-allman...,Did a Radio Host Tweet About Sodomizing a Park...,Crime,9 April 2018,Jamie Allman tweeted about sodomizing Parkland...,https://www.riverfronttimes.com/newsblog/2018/...,7,False,No Error,click to enlarge Screenshot via YouTube click ...,Jamie Allman Vows to 'Ram a Hot Poker' Up Park...,2018-04-06,Danny Wicentowski
187,true,https://www.snopes.com/fact-check/jamie-allman...,Did a Radio Host Tweet About Sodomizing a Park...,Crime,9 April 2018,Jamie Allman tweeted about sodomizing Parkland...,https://www.washingtonpost.com/news/arts-and-e...,13,False,No Error,A conservative commentator at a Sinclair Broad...,Sinclair show canceled after commentators vulg...,2018-04-09,Eli Rosenberg

In [20]:
df_test = df_test.sort_values(by=['article_category_phase1'])
df_test = df_test.drop_duplicates(keep='last')

In [21]:
df_test['fact_rating_phase1'].value_counts()

fact_rating_phase1
false           195
mostly false    104
mixture         102
unproven         63
true             44
mostly true      13
scam              2
legend            1
Name: count, dtype: int64

In [22]:
# df_test['fact_rating_phase1'].replace('mostly false', 'false', inplace=True)
df_test['fact_rating_phase1'].replace('mostly true', 'true', inplace=True)
df_test['fact_rating_phase1'].replace('unproven', 'true', inplace=True)

In [23]:
df_snopes = df_test[df_test['fact_rating_phase1'].isin(['false', 'true'])]

In [24]:
df_snopes['fact_rating_phase1'].value_counts()

fact_rating_phase1
false    195
true     120
Name: count, dtype: int64

In [25]:
df_snopes = df_snopes.rename(columns={'fact_rating_phase1':'label','article_title_phase1':'text'})

In [26]:
df_snopes = df_snopes[['text', 'label']].assign(metadata=df_snopes.iloc[:,2:].agg(dict,1))

In [27]:
df_snopes['label'].replace({'false':1, 'true':0}, inplace=True)

In [28]:
df_snopes.head()

,text,label,metadata
174,Was an Italian Economist Removed from a Plane ...,0,{'text': 'Was an Italian Economist Removed fro...
8524,Shelby Township Meijer Human Trafficking Warning,1,{'text': 'Shelby Township Meijer Human Traffic...
8523,Shelby Township Meijer Human Trafficking Warning,1,{'text': 'Shelby Township Meijer Human Traffic...
8522,Shelby Township Meijer Human Trafficking Warning,1,{'text': 'Shelby Township Meijer Human Traffic...
8521,Shelby Township Meijer Human Trafficking Warning,1,{'text': 'Shelby Township Meijer Human Traffic...

In [29]:
df_snopes['label'].value_counts()

label
1    195
0    120
Name: count, dtype: int64

In [30]:
df_snopes.to_feather('../data/snope.feather')