In [5]:
# If use jupyter notebook, cd to the path of the folder all-rnr-annotated-threads

D:\Projects\School\CSI4900\Fake-News-Detection\raw-data\pheme\all-rnr-annotated-threads

d:\Projects\School\CSI4900\Fake-News-Detection\.venv\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [6]:
%pip install numpy
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install pyarrow

Requirement already satisfied: numpy in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (1.24.1)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (2.1.4)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy<2,>=1.23.2 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from pandas) (1.24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (3.8.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: contourpy>=1.0.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (4.46.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (1.24.1)
Requirement already satisfied: packaging>=20.0 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (9.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (0.13.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy!=1.24.0,>=1.20 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from seaborn) (1.24.1)
Requirement already satisfied: pandas>=1.2 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from seaborn) (2.1.4)
Requirement already satisfied: matplotlib!=3.6.1,>=3.3 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from seaborn) (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (4.46.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (23.2)
Requirement already satisfied: pillow>=8 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (9.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.3->seaborn) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyarrow in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (14.0.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.16.6 in d:\projects\school\csi4900\fake-news-detection\.venv\lib\site-packages (from pyarrow) (1.24.1)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import json
import os

folds = [
    'charliehebdo-all-rnr-threads',
    'ottawashooting-all-rnr-threads',
    'ebola-essien-all-rnr-threads',
    'prince-toronto-all-rnr-threads',
    'ferguson-all-rnr-threads',	
    'putinmissing-all-rnr-threads',
    'germanwings-crash-all-rnr-threads',
    'gurlitt-all-rnr-threads',
    'sydneysiege-all-rnr-threads'
]


texts = []
fav_counts = []
retweet_counts = []
date = []

username = []
account_date = []
protected = []
verified = []
followers = []
followings = []
tweets_count = []

hashtag = []
url = []

events = []
y = []

def convert_annotations_data(annotation, string = True):
    label = None
    if 'is_rumour' in annotation.keys() and annotation['is_rumour'] == 'nonrumour':
        label = 'true'
    elif 'misinformation' in annotation.keys() and 'true'in annotation.keys():
        if int(annotation['misinformation'])==0 and int(annotation['true'])==0:
            if string:
                label = "unverified"
            else:
                label = 2
        elif int(annotation['misinformation'])==0 and int(annotation['true'])==1 :
            if string:
                label = "true"
            else:
                label = 1
        elif int(annotation['misinformation'])==1 and int(annotation['true'])==0 :
            if string:
                label = "false"
            else:
                label = 0
        elif int(annotation['misinformation'])==1 and int(annotation['true'])==1:
            print ("OMG! They both are 1!")
            print(annotation['misinformation'])
            print(annotation['true'])
            label = None
            
    elif 'misinformation' in annotation.keys() and 'true' not in annotation.keys():
        # all instances have misinfo label but don't have true label
        if int(annotation['misinformation'])==0:
            if string:
                label = "unverified"
            else:
                label = 2
        elif int(annotation['misinformation'])==1:
            if string:
                label = "false"
            else:
                label = 0
                
    elif 'true' in annotation.keys() and 'misinformation' not in annotation.keys():
        print ('Has true not misinformation')
    else:
        print('No annotations')
           
    return label

In [8]:
for f in folds:
  paths = [
     os.path.join('../../raw-data/pheme/all-rnr-annotated-threads', f, 'rumours'),
     os.path.join('../../raw-data/pheme/all-rnr-annotated-threads', f, 'non-rumours')
  ]
  for path in paths:
    for dir1 in os.listdir(path):
          if '_' not in dir1:
            path_target  = os.path.join(path,dir1,'annotation.json')
            file = open(path_target)
            data = json.load(file)
            target = convert_annotations_data(data)
            y.append(target)
            path2 = os.path.join(path, dir1,'source-tweets')
            for dir2 in os.listdir(path2):
              if '_' not in dir2:
                path3  = os.path.join(path2,dir2)
                file = open(path3)
                data = json.load(file)
              
                #tweet features
                text = data['text']
                tweet_date = data['created_at']
                fav = data['favorite_count']
                retw = data['retweet_count']
                  
                #user features
                usernames = data['user']['screen_name']
                account_creation = data['user']['created_at']
                is_protected = data['user']['protected']
                is_verified = data['user']['verified']
                no_followers = data['user']['followers_count']
                no_followings = data['user']['friends_count']
                no_tweets = data['user']['statuses_count']
                  
                #entities
                no_hashtags = len(data['entities']['hashtags'])      
                has_url = data['entities']['urls']      
    

                texts.append(text)
                date.append(tweet_date)
                fav_counts.append(fav)
                retweet_counts.append(retw)
                                      
                username.append(usernames)
                account_date.append(account_creation)
                protected.append(is_protected)
                verified.append(is_verified)
                followers.append(no_followers)
                followings.append(no_followings)
                tweets_count.append(no_tweets)
              
                
                hashtag.append(no_hashtags)
                url.append(has_url)
              
                events.append(f)

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../../raw-data/pheme/all-rnr-annotated-threads\\charliehebdo-all-rnr-threads\\rumours'

In [ ]:
df = pd.DataFrame([texts,date,fav_counts,retweet_counts,username,account_date,followers,followings,tweets_count,protected,verified,hashtag,url,events,y],['text','date','fav_count','retweet_count','username','account_date','followers','followings','tweet_count','protected','verified','no_hashtags','urls','event','target']).transpose()
df = df.infer_objects()
df.dropna(inplace=True)

In [ ]:
df.ino()

In [ ]:
len(df.index)

6424

In [ ]:
# original dataframe
df.head(5)

,text,date,fav_count,retweet_count,username,account_date,followers,followings,tweet_count,protected,verified,no_hashtags,urls,event,target
0,"Breaking: At least 10 dead, 5 injured after tO...",Wed Jan 07 11:06:08 +0000 2015,14,159,H_E_Samuel,Tue Oct 04 09:36:17 +0000 2011,1628,246,1901,False,False,0,[],charliehebdo-all-rnr-threads,true
1,France: 10 people dead after shooting at HQ of...,Wed Jan 07 11:07:51 +0000 2015,38,486,euronews,Wed Mar 18 12:57:11 +0000 2009,129573,337,48440,False,True,1,[],charliehebdo-all-rnr-threads,true
2,Ten killed in shooting at headquarters of Fren...,Wed Jan 07 11:08:09 +0000 2015,15,127,Channel4News,Mon Apr 28 14:29:37 +0000 2008,529882,3051,66682,False,True,1,[],charliehebdo-all-rnr-threads,true
3,BREAKING: 10 dead in shooting at headquarters ...,Wed Jan 07 11:09:50 +0000 2015,15,105,AlArabiya_Eng,Sat Feb 28 08:31:32 +0000 2009,499741,31,100466,False,True,2,[],charliehebdo-all-rnr-threads,true
4,Reuters: 10 people shot dead at headquarters o...,Wed Jan 07 11:11:16 +0000 2015,32,412,SkyNewsBreak,Wed Nov 04 11:25:45 +0000 2009,1377384,6,27228,False,True,1,[],charliehebdo-all-rnr-threads,true

In [ ]:
df.tail(5)

,text,date,fav_count,retweet_count,username,account_date,followers,followings,tweet_count,protected,verified,no_hashtags,urls,event,target
6420,Sydney siege ends as police storm Lindt Cafe a...,Mon Dec 15 15:55:59 +0000 2014,18,100,guardian,Thu Nov 05 23:49:19 +0000 2009,2997545,1081,102254,False,True,0,"[{'url': 'http://t.co/ek1EyHbJxA', 'indices': ...",sydneysiege-all-rnr-threads,true
6421,"Breaking News: #SydneySiege is over, according...",Mon Dec 15 15:56:41 +0000 2014,315,489,FoxNews,Sat Mar 17 19:01:26 +0000 2007,4636658,382,188589,False,True,1,"[{'url': 'http://t.co/7p9QLG6mn4', 'indices': ...",sydneysiege-all-rnr-threads,true
6422,Watch gunfire erupt and hostages flee chocolat...,Mon Dec 15 15:58:05 +0000 2014,91,181,NBCNews,Tue Mar 18 23:19:17 +0000 2008,1955488,2894,44356,False,True,1,"[{'url': 'http://t.co/Ju5h01y3R4', 'indices': ...",sydneysiege-all-rnr-threads,true
6423,Authorities have confirmed that #sydneysiege i...,Mon Dec 15 15:58:27 +0000 2014,35,117,YahooNewsUK,Fri Feb 13 15:44:54 +0000 2009,36137,926,14145,False,True,1,"[{'url': 'http://t.co/IrteddYrbH', 'indices': ...",sydneysiege-all-rnr-threads,true
6424,WATCH: The dramatic moment tactical teams stor...,Mon Dec 15 15:58:44 +0000 2014,93,117,PzFeed,Wed May 04 06:32:13 +0000 2011,201981,3540,21790,False,False,0,"[{'url': 'https://t.co/v8UYPgnyog', 'indices':...",sydneysiege-all-rnr-threads,true

In [ ]:
df['target'] = df['target'].replace(['unverified'], 'false')
array = ['false','true']
df_transform = pd.DataFrame(array,columns=['status'])
status_dict = df_transform['status'].unique().tolist()
df['target']=df['target'].apply(lambda x : status_dict.index(x))

df.head(5)

,text,date,fav_count,retweet_count,username,account_date,followers,followings,tweet_count,protected,verified,no_hashtags,urls,event,target
0,"Breaking: At least 10 dead, 5 injured after tO...",Wed Jan 07 11:06:08 +0000 2015,14,159,H_E_Samuel,Tue Oct 04 09:36:17 +0000 2011,1628,246,1901,False,False,0,[],charliehebdo-all-rnr-threads,1
1,France: 10 people dead after shooting at HQ of...,Wed Jan 07 11:07:51 +0000 2015,38,486,euronews,Wed Mar 18 12:57:11 +0000 2009,129573,337,48440,False,True,1,[],charliehebdo-all-rnr-threads,1
2,Ten killed in shooting at headquarters of Fren...,Wed Jan 07 11:08:09 +0000 2015,15,127,Channel4News,Mon Apr 28 14:29:37 +0000 2008,529882,3051,66682,False,True,1,[],charliehebdo-all-rnr-threads,1
3,BREAKING: 10 dead in shooting at headquarters ...,Wed Jan 07 11:09:50 +0000 2015,15,105,AlArabiya_Eng,Sat Feb 28 08:31:32 +0000 2009,499741,31,100466,False,True,2,[],charliehebdo-all-rnr-threads,1
4,Reuters: 10 people shot dead at headquarters o...,Wed Jan 07 11:11:16 +0000 2015,32,412,SkyNewsBreak,Wed Nov 04 11:25:45 +0000 2009,1377384,6,27228,False,True,1,[],charliehebdo-all-rnr-threads,1

In [ ]:
df = df.rename(columns={'target':'label', 'username': 'author', 'no_hashtags': 'hashtags'})
df.head(5)

,text,date,fav_count,retweet_count,author,account_date,followers,followings,tweet_count,protected,verified,hashtags,urls,event,label
0,"Breaking: At least 10 dead, 5 injured after tO...",Wed Jan 07 11:06:08 +0000 2015,14,159,H_E_Samuel,Tue Oct 04 09:36:17 +0000 2011,1628,246,1901,False,False,0,[],charliehebdo-all-rnr-threads,1
1,France: 10 people dead after shooting at HQ of...,Wed Jan 07 11:07:51 +0000 2015,38,486,euronews,Wed Mar 18 12:57:11 +0000 2009,129573,337,48440,False,True,1,[],charliehebdo-all-rnr-threads,1
2,Ten killed in shooting at headquarters of Fren...,Wed Jan 07 11:08:09 +0000 2015,15,127,Channel4News,Mon Apr 28 14:29:37 +0000 2008,529882,3051,66682,False,True,1,[],charliehebdo-all-rnr-threads,1
3,BREAKING: 10 dead in shooting at headquarters ...,Wed Jan 07 11:09:50 +0000 2015,15,105,AlArabiya_Eng,Sat Feb 28 08:31:32 +0000 2009,499741,31,100466,False,True,2,[],charliehebdo-all-rnr-threads,1
4,Reuters: 10 people shot dead at headquarters o...,Wed Jan 07 11:11:16 +0000 2015,32,412,SkyNewsBreak,Wed Nov 04 11:25:45 +0000 2009,1377384,6,27228,False,True,1,[],charliehebdo-all-rnr-threads,1

In [ ]:
# Order the columns in the dataframe to follow the following format
# text, label, author, metadata (where metadata is a key-value pair of everything else)
df = df[['text', 'label', 'author', 'date', 'fav_count', 'retweet_count', 'account_date', 'followers', 'followings', 'tweet_count', 'protected', 'verified', 'hashtags', 'urls', 'event']]
# metadata
df1 = df[['text', 'label', 'author']].assign(metadata=df.iloc[:,3:].agg(dict,1))
df1.head(5)

,text,label,author,metadata
0,"Breaking: At least 10 dead, 5 injured after tO...",1,H_E_Samuel,"{'date': 'Wed Jan 07 11:06:08 +0000 2015', 'fa..."
1,France: 10 people dead after shooting at HQ of...,1,euronews,"{'date': 'Wed Jan 07 11:07:51 +0000 2015', 'fa..."
2,Ten killed in shooting at headquarters of Fren...,1,Channel4News,"{'date': 'Wed Jan 07 11:08:09 +0000 2015', 'fa..."
3,BREAKING: 10 dead in shooting at headquarters ...,1,AlArabiya_Eng,"{'date': 'Wed Jan 07 11:09:50 +0000 2015', 'fa..."
4,Reuters: 10 people shot dead at headquarters o...,1,SkyNewsBreak,"{'date': 'Wed Jan 07 11:11:16 +0000 2015', 'fa..."

In [ ]:
# change false to 1 and true to 0
df1['label'] = df1['label'].apply(lambda x : 1 if x==0 else 0)
df1.head(5)

,text,label,author,metadata
0,"Breaking: At least 10 dead, 5 injured after tO...",0,H_E_Samuel,"{'date': 'Wed Jan 07 11:06:08 +0000 2015', 'fa..."
1,France: 10 people dead after shooting at HQ of...,0,euronews,"{'date': 'Wed Jan 07 11:07:51 +0000 2015', 'fa..."
2,Ten killed in shooting at headquarters of Fren...,0,Channel4News,"{'date': 'Wed Jan 07 11:08:09 +0000 2015', 'fa..."
3,BREAKING: 10 dead in shooting at headquarters ...,0,AlArabiya_Eng,"{'date': 'Wed Jan 07 11:09:50 +0000 2015', 'fa..."
4,Reuters: 10 people shot dead at headquarters o...,0,SkyNewsBreak,"{'date': 'Wed Jan 07 11:11:16 +0000 2015', 'fa..."

In [ ]:
df1.reset_index(drop=True, inplace=True)
df1.to_feather('pheme.feather')

In [ ]:
df1['label'].value_counts()

label
0    5089
1    1335
Name: count, dtype: int64